import {
  Student,
  DashboardStats,
  StudentStats,
  Assessment,
  QuestionLibrary,
  ActivityFeedItem,
  StudentReportItem,
  Question,
  Institution,
  Batch,
  StaffFaculty,
  AttendanceRecord,
  InstitutionAnnouncement,
} from './types';
export * from './mockInstitutionData';

export const mockInstitutions: Institution[] = [
  {
    id: 'inst-stanford',
    code: 'STANFORD',
    name: 'Stanford University',
    status: 'ACTIVE',
    primaryContactEmail: 'admin@stanford.edu',
    domains: ['stanford.edu', 'cs.stanford.edu', 'alumni.stanford.edu'],
    studentCount: 842,
    activeAssessmentsCount: 18,
    settings: {
      enforceDomainMatch: true,
      requireAttendanceGate: true,
      allowStudentSelfRegistration: false,
      flagThresholdForReview: 3,
    },
  },
  {
    id: 'inst-mit',
    code: 'MIT',
    name: 'Massachusetts Institute of Technology',
    status: 'ACTIVE',
    primaryContactEmail: 'assessment-office@mit.edu',
    domains: ['mit.edu', 'eecs.mit.edu'],
    studentCount: 620,
    activeAssessmentsCount: 14,
    settings: {
      enforceDomainMatch: true,
      requireAttendanceGate: true,
      allowStudentSelfRegistration: true,
      flagThresholdForReview: 3,
    },
  },
  {
    id: 'inst-ucb',
    code: 'UCB',
    name: 'UC Berkeley',
    status: 'ACTIVE',
    primaryContactEmail: 'exams@berkeley.edu',
    domains: ['berkeley.edu', 'cs.berkeley.edu'],
    studentCount: 512,
    activeAssessmentsCount: 12,
    settings: {
      enforceDomainMatch: true,
      requireAttendanceGate: false,
      allowStudentSelfRegistration: false,
      flagThresholdForReview: 2,
    },
  },
  {
    id: 'inst-cmu',
    code: 'CMU',
    name: 'Carnegie Mellon University',
    status: 'ACTIVE',
    primaryContactEmail: 'proctoring@cmu.edu',
    domains: ['cmu.edu', 'andrew.cmu.edu'],
    studentCount: 430,
    activeAssessmentsCount: 9,
    settings: {
      enforceDomainMatch: true,
      requireAttendanceGate: true,
      allowStudentSelfRegistration: false,
      flagThresholdForReview: 3,
    },
  },
  {
    id: 'inst-nus',
    code: 'NUS',
    name: 'National University of Singapore',
    status: 'ACTIVE',
    primaryContactEmail: 'examinations@nus.edu.sg',
    domains: ['nus.edu.sg', 'comp.nus.edu.sg', 'u.nus.edu'],
    studentCount: 310,
    activeAssessmentsCount: 7,
    settings: {
      enforceDomainMatch: true,
      requireAttendanceGate: true,
      allowStudentSelfRegistration: false,
      flagThresholdForReview: 2,
    },
  },
  {
    id: 'inst-acme',
    code: 'ACME',
    name: 'Acme Tech Global Hiring',
    status: 'ACTIVE',
    primaryContactEmail: 'talent-ops@acme.com',
    domains: ['acme.com', 'hire.acme.com'],
    studentCount: 133,
    activeAssessmentsCount: 5,
    settings: {
      enforceDomainMatch: false,
      requireAttendanceGate: false,
      allowStudentSelfRegistration: true,
      flagThresholdForReview: 1,
    },
  },
];

export const mockStudents: Student[] = [
  {
    id: 0,
    userId: "0a7ec044-3a0c-490b-b324-e128640cd62e",
    role: "student",
    createdAt: "7/25/2026, 10:02:25 AM",
    name: "Nanda Kumar",
    email: "nanda@talhelix.com",
    studentIdentifier: "TH-2026-9042",
    registerNumber: "710022104052",
    netId: "nkumar26",
    batchId: "batch-cs-26a",
    batchName: "CS 2026 - Section A",
    section: "A",
    institutionId: "inst-stanford",
    institutionName: "TalHelix Engineering Academy",
    institutionCode: "TALHELIX",
    dept: "Computer Science",
    batchYear: 2026,
    progress: 13,
    total: 20,
    score: 89,
    status: "Active",
    attendanceStatus: "PRESENT",
    flags: 0,
    lastActive: "Just now",
    avatarColor: "bg-blue-600",
    joinedDate: "2026-07-25",
    phone: "+1 (415) 890-2100",
    academicRecord: {
      cgpa: 3.88,
      attendancePercentage: 92.5,
      totalClasses: 40,
      attendedClasses: 37,
      assessmentsTaken: 18,
      assessmentsPassed: 18,
      avgAssessmentScore: 89.4,
      termHistory: [
        { term: 'Term 1', attendanceRate: 95.0, gpa: 3.9 },
        { term: 'Term 2', attendanceRate: 91.0, gpa: 3.85 },
        { term: 'Term 3', attendanceRate: 92.5, gpa: 3.88 },
      ],
    },
    activeDevices: [
      {
        sessionId: "sess-nanda-primary",
        deviceId: "dev-mbp-m3",
        deviceName: "MacBook Pro 16\" (macOS Sequoia)",
        deviceType: "DESKTOP",
        browser: "Chrome 128.0.6613",
        os: "macOS 15.0",
        ipAddress: "106.51.24.12",
        location: "Bengaluru, IN",
        loginTime: "Today, 10:02 AM",
        isCurrentSession: true,
        isPrimary: true,
      },
    ],
    assignments: [
      {
        id: "asg-nk-01",
        assessmentId: "asm-35de",
        assessmentUuid: "35de8266-eb28-43eb-99b8-9b03785f913e",
        assessmentTitle: "Technical Aptitude & DSA Assessment",
        institutionId: "inst-stanford",
        duration: 90,
        status: "ACTIVE",
        published: true,
        windowLabel: "anytime",
        assignedAt: "8/21/2026, 7:10:03 PM",
        assignedBy: "Admin Portal",
        validFrom: "2026-08-21T19:10:03Z",
        attendanceGated: true,
        attendanceStatus: "VERIFIED",
        attendanceVenue: "TalHelix Online Gate (IP Verified)",
        attendanceMarkedAt: "2026-08-21T19:15:00Z",
        sessionStatus: "not started",
        attempts: [],
      },
      {
        id: "asg-nk-02",
        assessmentId: "asm-2f20",
        assessmentUuid: "2f2036dd-0e3b-463d-82c4-94005a027875",
        assessmentTitle: "DSA & Technical Aptitude Assessment",
        institutionId: "inst-stanford",
        duration: 90,
        status: "ACTIVE",
        published: true,
        windowLabel: "anytime",
        assignedAt: "8/21/2026, 7:09:45 PM",
        assignedBy: "Admin Portal",
        validFrom: "2026-08-21T19:09:45Z",
        attendanceGated: true,
        attendanceStatus: "VERIFIED",
        sessionStatus: "not started",
        attempts: [],
      },
      {
        id: "asg-nk-03",
        assessmentId: "asm-d882",
        assessmentUuid: "d8826a4f-bfd5-45f6-b015-9e3a9dc6e44f",
        assessmentTitle: "Data Structures and Algorithms Competency Assessment",
        institutionId: "inst-stanford",
        duration: 120,
        status: "ACTIVE",
        published: true,
        windowLabel: "anytime",
        assignedAt: "8/21/2026, 2:57:41 PM",
        assignedBy: "Admin Portal",
        validFrom: "2026-08-21T14:57:41Z",
        attendanceGated: true,
        attendanceStatus: "VERIFIED",
        sessionStatus: "not started",
        attempts: [],
      },
      {
        id: "asg-nk-04",
        assessmentId: "asm-e753",
        assessmentUuid: "e753f4d3-5947-42b7-9ca7-8738facce1f6",
        assessmentTitle: "DSA Fundamentals: Time Complexity, Sorting, and Core Data Structures Quiz",
        institutionId: "inst-stanford",
        duration: 60,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "8/21/2026, 2:57:12 PM",
        assignedBy: "Admin Portal",
        validFrom: "2026-08-21T14:57:12Z",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        attendanceVenue: "TalHelix Exam Proctoring Lab",
        sessionStatus: "submitted",
        scoreSummary: { score: 92.0, maxScore: 100.0, percentage: 92.0 },
        startedAt: "8/21/2026, 3:02:10 PM",
        submittedAt: "8/21/2026, 3:45:18 PM",
        submissionsCount: 18,
        attempts: [
          {
            sessionId: "ses-e753-01",
            attemptNumber: 1,
            startedAt: "2026-08-21T15:02:10Z",
            submittedAt: "2026-08-21T15:45:18Z",
            score: 92.0,
            maxScore: 100,
            percentage: 92.0,
            passed: true,
            proctorVerdict: "CLEAR",
            flagsRecorded: 0,
            timeSpent: "43 mins",
          },
        ],
      },
      {
        id: "asg-nk-05",
        assessmentId: "asm-be8a",
        assessmentUuid: "be8ab82c-87bc-401e-a7ab-c90753f7873e",
        assessmentTitle: "TGL - KARUNYA - STEPX - DSA - COD - 2",
        institutionId: "inst-stanford",
        duration: 90,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "8/21/2026, 11:12:05 AM",
        assignedBy: "Admin Portal",
        validFrom: "2026-08-21T11:12:05Z",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        attendanceVenue: "Karunya Online Lab C",
        sessionStatus: "submitted",
        isCodingAssessment: true,
        scoreSummary: { score: 91.3, maxScore: 170.0, percentage: 53.7 },
        startedAt: "8/21/2026, 12:01:23 PM",
        submittedAt: "8/21/2026, 12:36:42 PM",
        submissionsCount: 37,
        attempts: [
          {
            sessionId: "ses-be8a-01",
            attemptNumber: 1,
            startedAt: "2026-08-21T12:01:23Z",
            submittedAt: "2026-08-21T12:36:42Z",
            score: 91.3,
            maxScore: 170.0,
            percentage: 53.7,
            passed: true,
            proctorVerdict: "CLEAR",
            flagsRecorded: 0,
            timeSpent: "35 mins",
          },
        ],
      },
      {
        id: "asg-nk-06",
        assessmentId: "asm-6920",
        assessmentUuid: "692053a5-cb34-47c7-93e6-b0979dcc6756",
        assessmentTitle: "TGL - KARUNYA - STEPX - DSA - COD - 2",
        institutionId: "inst-stanford",
        duration: 90,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "8/21/2026, 11:11:58 AM",
        assignedBy: "Admin Portal",
        validFrom: "2026-08-21T11:11:58Z",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        sessionStatus: "submitted",
        isCodingAssessment: true,
        scoreSummary: { score: 134.0, maxScore: 170.0, percentage: 78.8 },
        startedAt: "8/21/2026, 11:21:51 AM",
        submittedAt: "8/21/2026, 11:57:31 AM",
        submissionsCount: 50,
        attempts: [
          {
            sessionId: "ses-6920-01",
            attemptNumber: 1,
            startedAt: "2026-08-21T11:21:51Z",
            submittedAt: "2026-08-21T11:57:31Z",
            score: 134.0,
            maxScore: 170.0,
            percentage: 78.8,
            passed: true,
            proctorVerdict: "CLEAR",
            flagsRecorded: 0,
            timeSpent: "36 mins",
          },
        ],
      },
      {
        id: "asg-nk-07",
        assessmentId: "asm-47e3",
        assessmentUuid: "47e32a71-020b-4ca1-b50a-9e550d45bbe3",
        assessmentTitle: "MCQ",
        institutionId: "inst-stanford",
        duration: 45,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "8/12/2026, 12:21:24 PM",
        assignedBy: "Admin Portal",
        validFrom: "2026-08-12T12:21:24Z",
        attendanceGated: false,
        attendanceStatus: "CONSUMED",
        sessionStatus: "submitted",
        scoreSummary: { score: 85.0, maxScore: 100.0, percentage: 85.0 },
        startedAt: "8/12/2026, 12:25:00 PM",
        submittedAt: "8/12/2026, 1:10:00 PM",
        submissionsCount: 1,
        attempts: [],
      },
      {
        id: "asg-nk-08",
        assessmentId: "asm-fec5",
        assessmentUuid: "fec5585e-7342-4efe-9ef3-50cee3cbe737",
        assessmentTitle: "TGL - SVCE - STEPX - DSA - COD - 2",
        institutionId: "inst-stanford",
        duration: 60,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "8/6/2026, 6:25:14 PM",
        assignedBy: "Admin Portal",
        validFrom: "2026-08-06T18:25:14Z",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        sessionStatus: "submitted",
        isCodingAssessment: true,
        scoreSummary: { score: 100.0, maxScore: 100.0, percentage: 100.0 },
        startedAt: "8/6/2026, 7:04:22 PM",
        submittedAt: "8/6/2026, 7:14:22 PM",
        submissionsCount: 20,
        attempts: [],
      },
      {
        id: "asg-nk-09",
        assessmentId: "asm-104d",
        assessmentUuid: "104da7e2-2891-4cbd-82cf-b1a4ab3f9663",
        assessmentTitle: "TGL - SVCE - STEPX - DSA - COD - 2",
        institutionId: "inst-stanford",
        duration: 60,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "8/6/2026, 6:25:07 PM",
        assignedBy: "Admin Portal",
        validFrom: "2026-08-06T18:25:07Z",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        sessionStatus: "submitted",
        isCodingAssessment: true,
        scoreSummary: { score: 100.0, maxScore: 100.0, percentage: 100.0 },
        startedAt: "8/6/2026, 6:32:24 PM",
        submittedAt: "8/6/2026, 7:04:15 PM",
        submissionsCount: 27,
        attempts: [],
      },
      {
        id: "asg-nk-10",
        assessmentId: "asm-e740",
        assessmentUuid: "e74018d9-9d05-4b37-93c4-5d5b8323aaba",
        assessmentTitle: "STEP 1 - COD",
        institutionId: "inst-stanford",
        duration: 60,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "8/4/2026, 8:45:05 PM",
        assignedBy: "Admin Portal",
        validFrom: "2026-08-04T20:45:05Z",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        sessionStatus: "submitted",
        isCodingAssessment: true,
        scoreSummary: { score: 100.0, maxScore: 120.0, percentage: 83.3 },
        startedAt: "8/4/2026, 9:23:09 PM",
        submittedAt: "8/4/2026, 9:44:07 PM",
        submissionsCount: 21,
        attempts: [],
      },
      {
        id: "asg-nk-11",
        assessmentId: "asm-c3a8",
        assessmentUuid: "c3a819b4-1052-4e91-8841-33da56ec1089",
        assessmentTitle: "STEP 1 - COD",
        institutionId: "inst-stanford",
        duration: 60,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "8/4/2026, 8:44:50 PM",
        assignedBy: "Admin Portal",
        validFrom: "2026-08-04T20:44:50Z",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        sessionStatus: "submitted",
        isCodingAssessment: true,
        scoreSummary: { score: 80.0, maxScore: 120.0, percentage: 66.7 },
        startedAt: "8/4/2026, 8:47:07 PM",
        submittedAt: "8/4/2026, 9:11:03 PM",
        submissionsCount: 36,
        attempts: [],
      },
      {
        id: "asg-nk-12",
        assessmentId: "asm-b193",
        assessmentUuid: "b19358ef-3561-419a-9e12-89241b71239f",
        assessmentTitle: "STEP 1 - COD",
        institutionId: "inst-stanford",
        duration: 60,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "8/4/2026, 6:58:20 PM",
        assignedBy: "Admin Portal",
        validFrom: "2026-08-04T18:58:20Z",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        sessionStatus: "submitted",
        isCodingAssessment: true,
        scoreSummary: { score: 40.0, maxScore: 120.0, percentage: 33.3 },
        startedAt: "8/4/2026, 7:01:17 PM",
        submittedAt: "8/4/2026, 8:07:41 PM",
        submissionsCount: 34,
        attempts: [],
      },
      {
        id: "asg-nk-13",
        assessmentId: "asm-a571",
        assessmentUuid: "a5716e28-5912-4cf0-802b-2875ab63d410",
        assessmentTitle: "STEP 1 - COD",
        institutionId: "inst-stanford",
        duration: 60,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "8/4/2026, 5:58:10 PM",
        assignedBy: "Admin Portal",
        validFrom: "2026-08-04T17:58:10Z",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        sessionStatus: "submitted",
        isCodingAssessment: true,
        scoreSummary: { score: 54.5, maxScore: 120.0, percentage: 45.4 },
        startedAt: "8/4/2026, 6:00:27 PM",
        submittedAt: "8/4/2026, 7:00:54 PM",
        submissionsCount: 51,
        attempts: [],
      },
      {
        id: "asg-nk-14",
        assessmentId: "asm-94c2",
        assessmentUuid: "94c25a1b-3f21-4820-a330-9b0a8523c101",
        assessmentTitle: "System Design & Distributed Scalability Challenge",
        institutionId: "inst-stanford",
        duration: 75,
        status: "COMPLETED",
        published: true,
        windowLabel: "Aug 1 - Aug 30",
        assignedAt: "8/1/2026, 10:00:00 AM",
        assignedBy: "Admin Portal",
        validFrom: "2026-08-01T10:00:00Z",
        attendanceGated: false,
        attendanceStatus: "CONSUMED",
        sessionStatus: "submitted",
        scoreSummary: { score: 88.0, maxScore: 100.0, percentage: 88.0 },
        startedAt: "8/15/2026, 2:00:00 PM",
        submittedAt: "8/15/2026, 3:15:20 PM",
        submissionsCount: 1,
        attempts: [],
      },
      {
        id: "asg-nk-15",
        assessmentId: "asm-88e1",
        assessmentUuid: "88e1423b-2401-460d-8521-7c934251a92e",
        assessmentTitle: "Object-Oriented Programming in Java & C++",
        institutionId: "inst-stanford",
        duration: 90,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "7/28/2026, 9:30:00 AM",
        assignedBy: "Admin Portal",
        validFrom: "2026-07-28T09:30:00Z",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        sessionStatus: "submitted",
        scoreSummary: { score: 95.0, maxScore: 100.0, percentage: 95.0 },
        startedAt: "7/30/2026, 10:00:00 AM",
        submittedAt: "7/30/2026, 11:10:00 AM",
        submissionsCount: 14,
        attempts: [],
      },
      {
        id: "asg-nk-16",
        assessmentId: "asm-77f1",
        assessmentUuid: "77f1239c-1102-452a-9943-6c8431920bad",
        assessmentTitle: "Database Indexing & PostgreSQL Optimization",
        institutionId: "inst-stanford",
        duration: 60,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "7/26/2026, 4:15:00 PM",
        assignedBy: "Admin Portal",
        validFrom: "2026-07-26T16:15:00Z",
        attendanceGated: false,
        attendanceStatus: "CONSUMED",
        sessionStatus: "submitted",
        scoreSummary: { score: 90.0, maxScore: 100.0, percentage: 90.0 },
        startedAt: "7/27/2026, 9:00:00 AM",
        submittedAt: "7/27/2026, 9:48:30 AM",
        submissionsCount: 8,
        attempts: [],
      },
      {
        id: "asg-nk-17",
        assessmentId: "asm-66d9",
        assessmentUuid: "66d9238e-0912-421b-8732-5a7321094ce1",
        assessmentTitle: "React & Modern Frontend Architecture Quiz",
        institutionId: "inst-stanford",
        duration: 45,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "7/25/2026, 2:00:00 PM",
        assignedBy: "Admin Portal",
        validFrom: "2026-07-25T14:00:00Z",
        attendanceGated: false,
        attendanceStatus: "CONSUMED",
        sessionStatus: "submitted",
        scoreSummary: { score: 92.5, maxScore: 100.0, percentage: 92.5 },
        startedAt: "7/25/2026, 3:00:00 PM",
        submittedAt: "7/25/2026, 3:42:00 PM",
        submissionsCount: 1,
        attempts: [],
      },
      {
        id: "asg-nk-18",
        assessmentId: "asm-55c8",
        assessmentUuid: "55c8127f-9812-410a-7621-4b6210983ad2",
        assessmentTitle: "Computer Networks & TCP/IP Sockets Lab",
        institutionId: "inst-stanford",
        duration: 60,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "7/25/2026, 11:30:00 AM",
        assignedBy: "Admin Portal",
        validFrom: "2026-07-25T11:30:00Z",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        sessionStatus: "submitted",
        scoreSummary: { score: 84.0, maxScore: 100.0, percentage: 84.0 },
        startedAt: "7/25/2026, 1:00:00 PM",
        submittedAt: "7/25/2026, 1:55:00 PM",
        submissionsCount: 12,
        attempts: [],
      },
      {
        id: "asg-nk-19",
        assessmentId: "asm-44b7",
        assessmentUuid: "44b7016e-8721-409f-6510-3a5109872cb3",
        assessmentTitle: "Operating Systems Concurrency & Threads Benchmark",
        institutionId: "inst-stanford",
        duration: 90,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "7/25/2026, 10:15:00 AM",
        assignedBy: "Admin Portal",
        validFrom: "2026-07-25T10:15:00Z",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        sessionStatus: "submitted",
        scoreSummary: { score: 87.0, maxScore: 100.0, percentage: 87.0 },
        startedAt: "7/25/2026, 11:00:00 AM",
        submittedAt: "7/25/2026, 12:15:00 PM",
        submissionsCount: 19,
        attempts: [],
      },
      {
        id: "asg-nk-20",
        assessmentId: "asm-33a6",
        assessmentUuid: "33a6905d-7610-4f8e-5409-294098761ba4",
        assessmentTitle: "Cloud Security & IAM Governance Sprint",
        institutionId: "inst-stanford",
        duration: 60,
        status: "COMPLETED",
        published: true,
        windowLabel: "anytime",
        assignedAt: "7/25/2026, 10:05:00 AM",
        assignedBy: "Admin Portal",
        validFrom: "2026-07-25T10:05:00Z",
        attendanceGated: false,
        attendanceStatus: "CONSUMED",
        sessionStatus: "submitted",
        scoreSummary: { score: 91.0, maxScore: 100.0, percentage: 91.0 },
        startedAt: "7/25/2026, 10:10:00 AM",
        submittedAt: "7/25/2026, 10:58:00 AM",
        submissionsCount: 9,
        attempts: [],
      },
    ],
    flagsHistory: [],
    activityLogs: [
      {
        id: "act-nk-1",
        timestamp: "2026-08-31 10:02",
        ipAddress: "106.51.24.12",
        userAgent: "Chrome 128.0 (macOS)",
        event: "STUDENT_PORTAL_LOGIN",
        location: "Bengaluru, IN",
        status: "SUCCESS",
      },
    ],
  },
  {
    id: 1,
    name: "Alice Chen",
    email: "alice@stanford.edu",
    studentIdentifier: "SU-CS-2026-8819",
    institutionId: "inst-stanford",
    institutionName: "Stanford University",
    institutionCode: "STANFORD",
    dept: "Computer Science",
    batchYear: 2026,
    progress: 8,
    total: 12,
    score: 94,
    status: "Active",
    attendanceStatus: "PRESENT",
    flags: 0,
    lastActive: "2 hours ago",
    avatarColor: "bg-blue-600",
    joinedDate: "2024-01-15",
    phone: "+1 (650) 723-2300",
    activeDevices: [
      {
        sessionId: "sess-alice-mac",
        deviceId: "dev-mac-01",
        deviceName: "MacBook Pro 16\" (macOS)",
        deviceType: "DESKTOP",
        browser: "Chrome 128.0",
        os: "macOS Sonoma",
        ipAddress: "171.64.12.89",
        location: "Stanford, CA, US",
        loginTime: "Today, 08:30 AM",
        isCurrentSession: true,
      },
    ],
    assignments: [
      {
        id: "asg-101",
        assessmentId: "asm-1",
        assessmentTitle: "Algorithms & Complex Data Structures Diagnostic",
        institutionId: "inst-stanford",
        status: "COMPLETED",
        validFrom: "2026-08-10T08:00:00Z",
        validUntil: "2026-09-30T23:59:59Z",
        assignedAt: "2026-08-10T08:00:00Z",
        assignedBy: "Prof. John Hennessy",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        attendanceVenue: "Huang Eng Center Lab 104",
        attendanceMarkedAt: "2026-08-15T09:45:00Z",
        attendanceMarkedBy: "TA Marcus Vance",
        attempts: [
          {
            sessionId: "ses-99201",
            attemptNumber: 1,
            startedAt: "2026-08-15T10:00:00Z",
            submittedAt: "2026-08-15T11:42:15Z",
            score: 96.5,
            maxScore: 100,
            percentage: 96.5,
            passed: true,
            proctorVerdict: "CLEAR",
            flagsRecorded: 0,
            timeSpent: "1h 42m",
            venueCode: "LAB-104",
            attendanceVerifiedBy: "TA Marcus Vance",
          },
        ],
      },
      {
        id: "asg-102",
        assessmentId: "asm-2",
        assessmentTitle: "Python Backend & Microservices Architecture Test",
        institutionId: "inst-stanford",
        status: "ACTIVE",
        validFrom: "2026-08-20T00:00:00Z",
        validUntil: "2026-09-15T23:59:59Z",
        assignedAt: "2026-08-20T00:00:00Z",
        assignedBy: "Admin Portal",
        attendanceGated: true,
        attendanceStatus: "VERIFIED",
        attendanceVenue: "Gates CS Bldg Room 2B",
        attendanceMarkedAt: "2026-08-30T13:30:00Z",
        attendanceMarkedBy: "Proctor Sarah Jenkins",
        attempts: [],
      },
      {
        id: "asg-103",
        assessmentId: "asm-3",
        assessmentTitle: "Full-Stack System Design & Security Benchmark",
        institutionId: "inst-stanford",
        status: "ACTIVE",
        validFrom: "2026-08-25T00:00:00Z",
        validUntil: "2026-10-01T23:59:59Z",
        assignedAt: "2026-08-25T00:00:00Z",
        assignedBy: "Admin Portal",
        attendanceGated: true,
        attendanceStatus: "PENDING_CHECKIN",
        attempts: [],
      },
    ],
    flagsHistory: [],
    activityLogs: [
      {
        id: "act-1",
        timestamp: "2026-08-31 04:12",
        ipAddress: "171.64.12.89",
        userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/128.0.0.0",
        event: "STUDENT_PORTAL_LOGIN",
        location: "Stanford, CA, US",
        status: "SUCCESS",
      },
      {
        id: "act-2",
        timestamp: "2026-08-30 13:30",
        ipAddress: "171.64.12.89",
        userAgent: "Proctor Terminal #4 (RFID Scan)",
        event: "ATTENDANCE_CHECKIN",
        location: "Gates CS Bldg Room 2B",
        status: "SUCCESS",
      },
    ],
  },
  {
    id: 2,
    name: "Bob Kumar",
    email: "bkumar@mit.edu",
    studentIdentifier: "MIT-EECS-2025-4190",
    institutionId: "inst-mit",
    institutionName: "Massachusetts Institute of Technology",
    institutionCode: "MIT",
    dept: "Information Technology",
    batchYear: 2025,
    progress: 6,
    total: 12,
    score: 88,
    status: "In Progress",
    attendanceStatus: "CHECKED_IN",
    flags: 0,
    lastActive: "5 minutes ago",
    avatarColor: "bg-purple-600",
    joinedDate: "2024-02-01",
    phone: "+1 (617) 253-1000",
    activeDevices: [
      {
        sessionId: "sess-bob-thinkpad",
        deviceId: "dev-win-02",
        deviceName: "ThinkPad X1 Carbon (Windows 11)",
        deviceType: "DESKTOP",
        browser: "Edge 128.0",
        os: "Windows 11 Pro",
        ipAddress: "18.27.0.144",
        location: "Cambridge, MA, US",
        loginTime: "Today, 09:15 AM",
        isCurrentSession: true,
      },
    ],
    assignments: [
      {
        id: "asg-201",
        assessmentId: "asm-1",
        assessmentTitle: "Algorithms & Complex Data Structures Diagnostic",
        institutionId: "inst-mit",
        status: "COMPLETED",
        validFrom: "2026-08-01T00:00:00Z",
        validUntil: "2026-09-30T23:59:59Z",
        assignedAt: "2026-08-01T00:00:00Z",
        assignedBy: "MIT EECS Chair",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        attendanceVenue: "Stata Center Room 32-123",
        attendanceMarkedAt: "2026-08-12T14:00:00Z",
        attendanceMarkedBy: "Proctor Dr. Alan Bovik",
        attempts: [
          {
            sessionId: "ses-99202",
            attemptNumber: 1,
            startedAt: "2026-08-12T14:15:00Z",
            submittedAt: "2026-08-12T15:55:00Z",
            score: 88.0,
            maxScore: 100,
            percentage: 88.0,
            passed: true,
            proctorVerdict: "CLEAR",
            flagsRecorded: 1,
            timeSpent: "1h 40m",
            venueCode: "STATA-123",
            attendanceVerifiedBy: "Dr. Alan Bovik",
          },
        ],
      },
      {
        id: "asg-202",
        assessmentId: "asm-4",
        assessmentTitle: "Distributed Systems & Cloud Concurrency Examination",
        institutionId: "inst-mit",
        status: "ACTIVE",
        validFrom: "2026-08-20T00:00:00Z",
        validUntil: "2026-10-15T23:59:59Z",
        assignedAt: "2026-08-20T00:00:00Z",
        assignedBy: "MIT EECS Chair",
        attendanceGated: true,
        attendanceStatus: "PENDING_CHECKIN",
        attempts: [],
      },
    ],
    flagsHistory: [
      {
        id: "flg-201",
        studentId: 2,
        sessionId: "ses-99202",
        category: "TAB_SWITCH",
        reason: "Browser lost focus for 12 seconds during Section 1 (Algorithms)",
        flaggedBy: "TalHelix Student Portal (Automated)",
        source: "PORTAL_AUTO",
        timestamp: "2026-08-12 14:35",
        status: "RESOLVED",
        resolutionNotes: "Reviewed by Dr. Alan Bovik - OS notification dismiss verified, no unauthorized search detected.",
        resolvedBy: "Dr. Alan Bovik",
        resolvedAt: "2026-08-12 16:00",
      },
    ],
    activityLogs: [
      {
        id: "act-10",
        timestamp: "2026-08-31 06:37",
        ipAddress: "18.27.0.144",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/128.0.0.0",
        event: "STUDENT_PORTAL_LOGIN",
        location: "Cambridge, MA, US",
        status: "SUCCESS",
      },
    ],
  },
  {
    id: 3,
    name: "Carol Singh",
    email: "carol@berkeley.edu",
    studentIdentifier: "UCB-EECS-2026-1049",
    institutionId: "inst-ucb",
    institutionName: "UC Berkeley",
    institutionCode: "UCB",
    dept: "Computer Science",
    batchYear: 2026,
    progress: 10,
    total: 12,
    score: 91,
    status: "Active",
    attendanceStatus: "PRESENT",
    flags: 0,
    lastActive: "1 day ago",
    avatarColor: "bg-emerald-600",
    joinedDate: "2024-01-20",
    phone: "+1 (510) 642-6000",
    activeDevices: [
      {
        sessionId: "sess-carol-air",
        deviceId: "dev-mac-03",
        deviceName: "MacBook Air (Safari 17)",
        deviceType: "DESKTOP",
        browser: "Safari 17.4",
        os: "macOS Sonoma",
        ipAddress: "128.32.0.50",
        location: "Berkeley, CA, US",
        loginTime: "Yesterday, 02:10 PM",
        isCurrentSession: true,
      },
    ],
    assignments: [
      {
        id: "asg-301",
        assessmentId: "asm-1",
        assessmentTitle: "Algorithms & Complex Data Structures Diagnostic",
        institutionId: "inst-ucb",
        status: "COMPLETED",
        validFrom: "2026-08-05T00:00:00Z",
        validUntil: "2026-09-30T23:59:59Z",
        assignedAt: "2026-08-05T00:00:00Z",
        assignedBy: "Prof. Dan Garcia",
        attendanceGated: false,
        attendanceStatus: "CONSUMED",
        attempts: [
          {
            sessionId: "ses-99203",
            attemptNumber: 1,
            startedAt: "2026-08-10T11:00:00Z",
            submittedAt: "2026-08-10T12:20:00Z",
            score: 91.0,
            maxScore: 100,
            percentage: 91.0,
            passed: true,
            proctorVerdict: "CLEAR",
            flagsRecorded: 0,
            timeSpent: "1h 20m",
          },
        ],
      },
    ],
    flagsHistory: [],
    activityLogs: [
      {
        id: "act-20",
        timestamp: "2026-08-30 09:12",
        ipAddress: "128.32.0.50",
        userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
        event: "STUDENT_PORTAL_LOGIN",
        location: "Berkeley, CA, US",
        status: "SUCCESS",
      },
    ],
  },
  {
    id: 4,
    name: "David Lee",
    email: "david@andrew.cmu.edu",
    studentIdentifier: "CMU-SCS-2025-9921",
    institutionId: "inst-cmu",
    institutionName: "Carnegie Mellon University",
    institutionCode: "CMU",
    dept: "Electronics",
    batchYear: 2025,
    progress: 4,
    total: 12,
    score: 72,
    status: "Inactive",
    attendanceStatus: "ABSENT",
    flags: 3,
    lastActive: "1 week ago",
    avatarColor: "bg-amber-600",
    joinedDate: "2023-11-10",
    phone: "+1 (412) 268-2000",
    activeDevices: [],
    assignments: [
      {
        id: "asg-401",
        assessmentId: "asm-2",
        assessmentTitle: "Python Backend & Microservices Architecture Test",
        institutionId: "inst-cmu",
        status: "COMPLETED",
        validFrom: "2026-08-01T00:00:00Z",
        validUntil: "2026-09-01T23:59:59Z",
        assignedAt: "2026-08-01T00:00:00Z",
        assignedBy: "CMU Dean of SCS",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        attendanceVenue: "Gates Hillman Center 4401",
        attendanceMarkedAt: "2026-08-08T09:00:00Z",
        attendanceMarkedBy: "Proctor Rachel Stern",
        attempts: [
          {
            sessionId: "ses-99204",
            attemptNumber: 1,
            startedAt: "2026-08-08T09:30:00Z",
            submittedAt: "2026-08-08T11:15:00Z",
            score: 72.0,
            maxScore: 100,
            percentage: 72.0,
            passed: true,
            proctorVerdict: "SUSPICIOUS",
            flagsRecorded: 3,
            timeSpent: "1h 45m",
            venueCode: "GHC-4401",
            attendanceVerifiedBy: "Proctor Rachel Stern",
          },
        ],
      },
    ],
    flagsHistory: [
      {
        id: "flg-401",
        studentId: 4,
        sessionId: "ses-99204",
        category: "TAB_SWITCH",
        reason: "3 separate tab focus losses recorded during Section 2 (Microservices)",
        flaggedBy: "TalHelix Student Portal (Automated)",
        source: "PORTAL_AUTO",
        timestamp: "2026-08-08 09:45",
        status: "ACTIVE",
      },
      {
        id: "flg-402",
        studentId: 4,
        sessionId: "ses-99204",
        category: "MULTIPLE_FACES",
        reason: "Secondary face recognized by proctoring webcam model for 28 seconds",
        flaggedBy: "TalHelix Vision Guard",
        source: "PORTAL_AUTO",
        timestamp: "2026-08-08 10:15",
        status: "ACTIVE",
      },
      {
        id: "flg-403",
        studentId: 4,
        sessionId: "ses-99204",
        category: "FULLSCREEN_EXIT",
        reason: "Full-screen mode reduced / window minimized during test execution",
        flaggedBy: "TalHelix Student Portal (Automated)",
        source: "PORTAL_AUTO",
        timestamp: "2026-08-08 10:48",
        status: "ACTIVE",
      },
    ],
    activityLogs: [
      {
        id: "act-30",
        timestamp: "2026-08-24 16:40",
        ipAddress: "128.2.0.12",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64)",
        event: "STUDENT_PORTAL_LOGIN",
        location: "Pittsburgh, PA, US",
        status: "SUCCESS",
      },
    ],
  },
  {
    id: 5,
    name: "Eva Martinez",
    email: "eva@u.nus.edu",
    studentIdentifier: "NUS-SOC-2026-3021",
    institutionId: "inst-nus",
    institutionName: "National University of Singapore",
    institutionCode: "NUS",
    dept: "Computer Science",
    batchYear: 2026,
    progress: 7,
    total: 12,
    score: 83,
    status: "Active",
    attendanceStatus: "PRESENT",
    flags: 0,
    lastActive: "3 hours ago",
    avatarColor: "bg-rose-600",
    joinedDate: "2024-03-05",
    phone: "+65 6516 6666",
    activeDevices: [
      {
        sessionId: "sess-eva-dell",
        deviceId: "dev-dell-05",
        deviceName: "Dell XPS 15 (Chrome 128)",
        deviceType: "DESKTOP",
        browser: "Chrome 128.0",
        os: "Windows 11",
        ipAddress: "137.132.0.21",
        location: "Singapore, SG",
        loginTime: "Today, 10:00 AM",
        isCurrentSession: true,
      },
    ],
    assignments: [
      {
        id: "asg-501",
        assessmentId: "asm-1",
        assessmentTitle: "Algorithms & Complex Data Structures Diagnostic",
        institutionId: "inst-nus",
        status: "ACTIVE",
        validFrom: "2026-08-15T00:00:00Z",
        validUntil: "2026-10-15T23:59:59Z",
        assignedAt: "2026-08-15T00:00:00Z",
        assignedBy: "NUS SOC Examinations",
        attendanceGated: true,
        attendanceStatus: "PENDING_CHECKIN",
        attempts: [],
      },
    ],
    flagsHistory: [],
    activityLogs: [
      {
        id: "act-40",
        timestamp: "2026-08-31 03:20",
        ipAddress: "137.132.0.21",
        userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
        event: "STUDENT_PORTAL_LOGIN",
        location: "Singapore, SG",
        status: "SUCCESS",
      },
    ],
  },
  {
    id: 6,
    name: "Frank Wilson",
    email: "fwilson@acme.com",
    studentIdentifier: "ACME-ENG-2026-0044",
    institutionId: "inst-acme",
    institutionName: "Acme Tech Global Hiring",
    institutionCode: "ACME",
    dept: "Information Technology",
    batchYear: 2026,
    progress: 5,
    total: 12,
    score: 85,
    status: "In Progress",
    attendanceStatus: "PRESENT",
    flags: 2,
    lastActive: "Just now",
    avatarColor: "bg-indigo-600",
    joinedDate: "2024-02-18",
    phone: "+1 (415) 555-0199",
    activeDevices: [
      {
        sessionId: "sess-frank-desktop",
        deviceId: "dev-frank-pc",
        deviceName: "Dell Precision Tower (Chrome 128)",
        deviceType: "DESKTOP",
        browser: "Chrome 128.0",
        os: "Windows 11 Pro",
        ipAddress: "198.51.100.24",
        location: "San Francisco, CA, US",
        loginTime: "Today, 09:40 AM",
        isCurrentSession: true,
      },
      {
        sessionId: "sess-frank-phone",
        deviceId: "dev-frank-mobile",
        deviceName: "iPhone 15 Pro (Mobile Safari)",
        deviceType: "MOBILE",
        browser: "Mobile Safari 17.5",
        os: "iOS 17.5",
        ipAddress: "198.51.100.88",
        location: "San Francisco, CA, US",
        loginTime: "Today, 09:55 AM",
        isCurrentSession: false,
      },
    ],
    assignments: [
      {
        id: "asg-601",
        assessmentId: "asm-2",
        assessmentTitle: "Python Backend & Microservices Architecture Test",
        institutionId: "inst-acme",
        status: "ACTIVE",
        validFrom: "2026-08-20T00:00:00Z",
        validUntil: "2026-09-20T23:59:59Z",
        assignedAt: "2026-08-20T00:00:00Z",
        assignedBy: "Acme Talent Recruiter",
        attendanceGated: false,
        attendanceStatus: "VERIFIED",
        attempts: [],
      },
    ],
    flagsHistory: [
      {
        id: "flg-frank-devices",
        studentId: 6,
        category: "MULTIPLE_DEVICES",
        reason: "Multiple active device logins detected on portal (2 devices: Dell Precision + iPhone 15 Pro). Portal requires single-device session.",
        flaggedBy: "TalHelix Student Portal (Automated)",
        source: "PORTAL_AUTO",
        timestamp: "2026-08-31 09:55",
        status: "ACTIVE",
        autoRevokeOnSingleDevice: true,
      },
      {
        id: "flg-601",
        studentId: 6,
        category: "SEB_BREACH",
        reason: "Safe Exam Browser configuration check warning during candidate environment test",
        flaggedBy: "SEB Integrity Engine",
        source: "SEB_CLIENT",
        timestamp: "2026-08-20 11:00",
        status: "ACTIVE",
      },
    ],
    activityLogs: [
      {
        id: "act-50",
        timestamp: "2026-08-31 09:55",
        ipAddress: "198.51.100.88",
        userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 17_5 like Mac OS X) AppleWebKit/605.1.15",
        event: "MULTIPLE_DEVICE_DETECTED",
        location: "San Francisco, CA, US",
        status: "WARNING",
      },
      {
        id: "act-51",
        timestamp: "2026-08-31 09:40",
        ipAddress: "198.51.100.24",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64) Chrome/128.0.0.0",
        event: "STUDENT_PORTAL_LOGIN",
        location: "San Francisco, CA, US",
        status: "SUCCESS",
      },
    ],
  },
  {
    id: 7,
    name: "Elena Rostova",
    email: "elena.r@stanford.edu",
    studentIdentifier: "SU-CS-2026-9104",
    institutionId: "inst-stanford",
    institutionName: "Stanford University",
    institutionCode: "STANFORD",
    dept: "Computer Science",
    batchYear: 2026,
    progress: 9,
    total: 12,
    score: 97,
    status: "Active",
    attendanceStatus: "PRESENT",
    flags: 0,
    lastActive: "40 minutes ago",
    avatarColor: "bg-emerald-600",
    joinedDate: "2024-01-18",
    phone: "+1 (650) 723-9912",
    activeDevices: [
      {
        sessionId: "sess-elena-mac",
        deviceId: "dev-mac-07",
        deviceName: "MacBook Pro 14\" (Chrome 128)",
        deviceType: "DESKTOP",
        browser: "Chrome 128.0",
        os: "macOS Sonoma",
        ipAddress: "171.64.12.92",
        location: "Stanford, CA, US",
        loginTime: "Today, 06:00 AM",
        isCurrentSession: true,
      },
    ],
    assignments: [
      {
        id: "asg-701",
        assessmentId: "asm-1",
        assessmentTitle: "Algorithms & Complex Data Structures Diagnostic",
        institutionId: "inst-stanford",
        status: "COMPLETED",
        validFrom: "2026-08-10T00:00:00Z",
        validUntil: "2026-09-30T23:59:59Z",
        assignedAt: "2026-08-10T00:00:00Z",
        assignedBy: "Prof. John Hennessy",
        attendanceGated: true,
        attendanceStatus: "CONSUMED",
        attendanceVenue: "Huang Eng Center Lab 104",
        attendanceMarkedAt: "2026-08-15T09:45:00Z",
        attendanceMarkedBy: "TA Marcus Vance",
        attempts: [
          {
            sessionId: "ses-99207",
            attemptNumber: 1,
            startedAt: "2026-08-15T10:00:00Z",
            submittedAt: "2026-08-15T11:28:40Z",
            score: 98.0,
            maxScore: 100,
            percentage: 98.0,
            passed: true,
            proctorVerdict: "CLEAR",
            flagsRecorded: 0,
            timeSpent: "1h 28m",
            venueCode: "LAB-104",
            attendanceVerifiedBy: "TA Marcus Vance",
          },
        ],
      },
    ],
    flagsHistory: [],
    activityLogs: [
      {
        id: "act-70",
        timestamp: "2026-08-31 06:00",
        ipAddress: "171.64.12.92",
        userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
        event: "STUDENT_PORTAL_LOGIN",
        location: "Stanford, CA, US",
        status: "SUCCESS",
      },
    ],
  },
  {
    id: 8,
    name: "Tariq Al-Mansoor",
    email: "tariq@eecs.mit.edu",
    studentIdentifier: "MIT-EECS-2025-7720",
    institutionId: "inst-mit",
    institutionName: "Massachusetts Institute of Technology",
    institutionCode: "MIT",
    dept: "Computer Science",
    batchYear: 2025,
    progress: 7,
    total: 12,
    score: 90,
    status: "Active",
    attendanceStatus: "PENDING",
    flags: 0,
    lastActive: "1 hour ago",
    avatarColor: "bg-blue-600",
    joinedDate: "2024-02-10",
    phone: "+1 (617) 253-8890",
    activeDevices: [
      {
        sessionId: "sess-tariq-laptop",
        deviceId: "dev-tariq-01",
        deviceName: "Dell XPS 13 (Ubuntu Linux)",
        deviceType: "DESKTOP",
        browser: "Firefox 129.0",
        os: "Ubuntu 24.04 LTS",
        ipAddress: "18.27.0.210",
        location: "Cambridge, MA, US",
        loginTime: "Today, 06:15 AM",
        isCurrentSession: true,
      },
    ],
    assignments: [],
    flagsHistory: [],
    activityLogs: [],
  },
];

export const mockDashboardStats: DashboardStats = {
  activeTenants: 7,
  totalUsers: 33980,
  activeUsers: 33799,
  assessments: 506,
  published: 462,
  draft: 44,
};

export const mockStudentStats: StudentStats = {
  total: 2847,
  activeToday: 156,
  avgScore: 78.5,
  completionRate: 84,
};

export const sampleQuestions: Question[] = [
  {
    id: "q-coding-1",
    title: "Find the Next Term in an Alternating Increasing Difference Series",
    type: "CODING",
    difficulty: "EASY",
    marks: 10,
    negativeMarks: 0,
    requireReasoning: false,
    language: "python",
    codeTemplates: {
      python: `# Function 1: Generate Series
def generateSeries(arr, n):
    if n <= 0:
        return
    current_val = 2
    arr[0] = current_val
    for i in range(1, n):
        current_val += 3 * i
        arr[i] = current_val * (1 if i % 2 == 0 else -1)

# Function 2: Sum up to index
def sum_up_to_index(arr, index):
    s = 0
    for i in range(index):
        s = s + arr[i]
    return s

# Main function
def main():
    # Read input
    n, index = map(int, input().split())
    # Initialize array
    arr = [0] * n
    # Generate the series
    generateSeries(arr, n)
`,
    },
    stemMarkdown: `You are given a numerical series: \`2, -5, 11, -20, 32, -47, 65, -86, 110, -137, 167, ...\`

Your task is to identify the pattern in the series and write a function that generates the first \`N\` terms of this series, storing them inside a given array.

### Explanation of the Pattern:
The series follows two key mathematical logic patterns:

1. **Alternating Signs** The terms alternate between positive and negative, starting with a positive number.
2. **Increasing Differences** The absolute values of the terms progressively increase with a growing difference:
   - 2 to 5 → difference = 3
   - 5 to 11 → difference = 6
   - 11 to 20 → difference = 9
   - 20 to 32 → difference = 12
   - 32 to 47 → difference = 15

The difference between terms grows linearly by 3 every step.

**Your Goal:** Populate the array up to \`N\` terms based on this pattern. *Note: Do NOT write any output/print statements in your function. The \`main\` method is already fully prepared to handle input, invoke your sequence generator, and additionally compute and print the sum of the sequence up to a given \`index\`.*

### Input Format
A single line containing two space-separated integers \`n\` (the number of terms to generate) and \`index\` (the number of terms to sum).

### Output Format
A single line containing the first \`n\` terms of the series and the sum up to \`index\`.`,
    codeTemplate: `# Function 1: Generate Series
def generateSeries(arr, n):
    if n <= 0:
        return
    current_val = 2
    arr[0] = current_val
    for i in range(1, n):
        current_val += 3 * i
        arr[i] = current_val * (1 if i % 2 == 0 else -1)

# Function 2: Sum up to index
def sum_up_to_index(arr, index):
    s = 0
    for i in range(index):
        s = s + arr[i]
    return s

# Main function
def main():
    # Read input
    n, index = map(int, input().split())
    # Initialize array
    arr = [0] * n
    # Generate the series
    generateSeries(arr, n)
`,
    testCases: [
      { id: "tc-1", input: "6 4", expectedOutput: "[2, -5, 11, -20, 32, -47]\nSum: -12", isHidden: false, marks: 3 },
      { id: "tc-2", input: "10 5", expectedOutput: "[2, -5, 11, -20, 32, -47, 65, -86, 110, -137]\nSum: 20", isHidden: false, marks: 3 },
      { id: "tc-3", input: "12 10", expectedOutput: "[2, -5, 11, -20, 32, -47, 65, -86, 110, -137, 167, -200]\nSum: -45", isHidden: true, marks: 4 },
    ],
    options: [],
  },
  {
    id: "q-101",
    title: "Python List Comprehensions & Immutability",
    type: "MCQ",
    difficulty: "MEDIUM",
    marks: 2,
    negativeMarks: 0.5,
    requireReasoning: true,
    stemMarkdown: "Given the following Python code snippet:\n\n```python\nnums = [1, 2, 3, 4, 5]\nresult = [x * 2 for x in nums if x % 2 == 1]\nprint(result)\n```\n\nWhat is the exact output printed to standard output?",
    options: [
      { id: "opt-1", text: "`[2, 6, 10]`", isCorrect: true },
      { id: "opt-2", text: "`[4, 8]`", isCorrect: false },
      { id: "opt-3", text: "`[1, 3, 5]`", isCorrect: false },
      { id: "opt-4", text: "`[2, 4, 6, 8, 10]`", isCorrect: false },
    ],
  },
  {
    id: "q-102",
    title: "SQL Index Optimization & Query Plans",
    type: "MCQ",
    difficulty: "HARD",
    marks: 3,
    negativeMarks: 1,
    requireReasoning: false,
    stemMarkdown: "Which of the following index structures is most suitable for range queries over continuously ordered timestamp columns?",
    options: [
      { id: "opt-201", text: "B-Tree Index (`CREATE INDEX ... USING btree`)", isCorrect: true },
      { id: "opt-202", text: "Hash Index (`USING hash`)", isCorrect: false },
      { id: "opt-203", text: "Bloom Filter Index", isCorrect: false },
      { id: "opt-204", text: "BitMap Index without sorting", isCorrect: false },
    ],
  },
  {
    id: "q-103",
    title: "Time Complexity of Binary Search",
    type: "MCQ",
    difficulty: "EASY",
    marks: 1,
    negativeMarks: 0,
    requireReasoning: false,
    stemMarkdown: "What is the **worst-case** time complexity of searching an element in a sorted array of size $N$ using standard Binary Search?",
    options: [
      { id: "opt-301", text: "`O(log N)`", isCorrect: true },
      { id: "opt-302", text: "`O(N)`", isCorrect: false },
      { id: "opt-303", text: "`O(N log N)`", isCorrect: false },
      { id: "opt-304", text: "`O(1)`", isCorrect: false },
    ],
  },
];

export const mockAssessments: Assessment[] = [
  {
    id: "asm-1",
    title: "Python Basics — Week 1",
    description: "Fundamental syntax, variables, data types, and control flow in Python 3.11+.",
    instructions: "Read all questions carefully. Calculator is permitted. No external IDE allowed.",
    duration: 45,
    passingScore: 60,
    kind: "Standard — mixed MCQ / MSQ / Fill-in / Scenario",
    publishImmediately: true,
    requireSafeExamBrowser: true,
    category: "Programming",
    status: "Published",
    questionsCount: 15,
    createdAt: "2024-05-10",
    questions: sampleQuestions,
    assignedCount: 4,
    completedCount: 3,
    inProgressCount: 1,
    assignedStudentIds: [1, 2, 3, 5],
  },
  {
    id: "asm-2",
    title: "Core Java & OOP Concepts",
    description: "Polymorphism, Inheritance, Encapsulation, Generics, and JVM memory lifecycle.",
    instructions: "Answer all 20 questions. Time limit is strictly enforced.",
    duration: 60,
    passingScore: 70,
    kind: "Standard — mixed MCQ / MSQ / Fill-in / Scenario",
    publishImmediately: true,
    requireSafeExamBrowser: true,
    category: "Programming",
    status: "Published",
    questionsCount: 20,
    createdAt: "2024-05-12",
    questions: sampleQuestions,
    assignedCount: 3,
    completedCount: 1,
    inProgressCount: 2,
    assignedStudentIds: [1, 4, 6],
  },
  {
    id: "asm-3",
    title: "Relational Database Design & SQL",
    description: "Normalization (1NF-3NF/BCNF), indexing strategies, transactions (ACID), and complex JOINs.",
    instructions: "Includes interactive SQL query assessment sections.",
    duration: 50,
    passingScore: 65,
    kind: "Standard — mixed MCQ / MSQ / Fill-in / Scenario",
    publishImmediately: true,
    requireSafeExamBrowser: true,
    category: "Database",
    status: "Published",
    questionsCount: 18,
    createdAt: "2024-05-15",
    questions: sampleQuestions,
    assignedCount: 2,
    completedCount: 0,
    inProgressCount: 1,
    assignedStudentIds: [2, 3],
  },
  {
    id: "asm-4",
    title: "Cloud Infrastructure & DevOps Essentials",
    description: "Containerization with Docker, Kubernetes orchestration, CI/CD pipelines, and IAM policies.",
    instructions: "Scenario-based questions regarding high-availability system architecture.",
    duration: 40,
    passingScore: 50,
    kind: "Standard — mixed MCQ / MSQ / Fill-in / Scenario",
    publishImmediately: false,
    requireSafeExamBrowser: true,
    category: "Cloud",
    status: "Draft",
    questionsCount: 12,
    createdAt: "2024-05-18",
    questions: sampleQuestions,
    assignedCount: 0,
    completedCount: 0,
    inProgressCount: 0,
    assignedStudentIds: [],
  },
  {
    id: "asm-5",
    title: "Data Structures & Algorithms Sprint",
    description: "Trees, Graphs, Dynamic Programming, and Greedy Algorithms with asymptotic analysis.",
    instructions: "Scratchpad provided in the safe exam browser environment.",
    duration: 90,
    passingScore: 75,
    kind: "Standard — mixed MCQ / MSQ / Fill-in / Scenario",
    publishImmediately: true,
    requireSafeExamBrowser: true,
    category: "Computer Science",
    status: "Published",
    questionsCount: 25,
    createdAt: "2024-05-20",
    questions: sampleQuestions,
    assignedCount: 5,
    completedCount: 2,
    inProgressCount: 1,
    assignedStudentIds: [1, 2, 3, 4, 5],
  },
  {
    id: "asm-6",
    title: "Full-Stack Web Architecture & APIs",
    description: "RESTful principles, GraphQL, WebSockets, JWT authentication, and browser rendering pipelines.",
    instructions: "Review code snippets carefully before submitting choices.",
    duration: 60,
    passingScore: 60,
    kind: "Standard — mixed MCQ / MSQ / Fill-in / Scenario",
    publishImmediately: false,
    requireSafeExamBrowser: true,
    category: "Web Development",
    status: "Draft",
    questionsCount: 16,
    createdAt: "2024-05-22",
    questions: sampleQuestions,
    assignedCount: 0,
    completedCount: 0,
    inProgressCount: 0,
    assignedStudentIds: [],
  },
];

export const mockLibraries: QuestionLibrary[] = [
  {
    id: "lib-1",
    name: "Core Java & Spring Boot Questions",
    description: "Reusable multi-level questions covering OOP, Collections, Concurrency, and Spring REST APIs.",
    questionCount: 128,
    createdAt: "2024-02-14",
    category: "Backend Development",
    questions: sampleQuestions,
  },
  {
    id: "lib-2",
    name: "Python for Data Science & AI",
    description: "NumPy vectorization, Pandas dataframes, Matplotlib charts, and scikit-learn models.",
    questionCount: 94,
    createdAt: "2024-03-01",
    category: "Data Science",
    questions: sampleQuestions,
  },
  {
    id: "lib-3",
    name: "Relational DB & SQL Mastery",
    description: "PostgreSQL and MySQL querying, index optimization, query planning, and schema design.",
    questionCount: 86,
    createdAt: "2024-03-20",
    category: "Database",
    questions: sampleQuestions,
  },
  {
    id: "lib-4",
    name: "Quantitative Aptitude & Logic",
    description: "Problem solving, permutations & combinations, probability, data interpretation, and deductive logic.",
    questionCount: 210,
    createdAt: "2024-04-05",
    category: "Aptitude",
    questions: sampleQuestions,
  },
  {
    id: "lib-5",
    name: "Modern Frontend (React & TypeScript)",
    description: "Hooks, state managers, rendering performance, accessibility (a11y), and Tailwind CSS.",
    questionCount: 65,
    createdAt: "2024-04-28",
    category: "Frontend",
    questions: sampleQuestions,
  },
];

export const mockActivityFeed: ActivityFeedItem[] = [
  {
    id: "act-1",
    studentName: "Alice Chen",
    studentEmail: "alice@example.com",
    studentAvatar: "AC",
    assessmentTitle: "Python Basics — Week 1",
    score: 94,
    passed: true,
    timeAgo: "12 mins ago",
    timestamp: "2024-05-25 14:48",
  },
  {
    id: "act-2",
    studentName: "Bob Kumar",
    studentEmail: "bob@example.com",
    studentAvatar: "BK",
    assessmentTitle: "Core Java & OOP Concepts",
    score: 86,
    passed: true,
    timeAgo: "28 mins ago",
    timestamp: "2024-05-25 14:32",
  },
  {
    id: "act-3",
    studentName: "Frank Wilson",
    studentEmail: "frank@example.com",
    studentAvatar: "FW",
    assessmentTitle: "Relational Database Design & SQL",
    score: 82,
    passed: true,
    timeAgo: "1 hour ago",
    timestamp: "2024-05-25 14:00",
  },
  {
    id: "act-4",
    studentName: "Carol Singh",
    studentEmail: "carol@example.com",
    studentAvatar: "CS",
    assessmentTitle: "Data Structures & Algorithms Sprint",
    score: 90,
    passed: true,
    timeAgo: "2 hours ago",
    timestamp: "2024-05-25 13:00",
  },
  {
    id: "act-5",
    studentName: "Eva Martinez",
    studentEmail: "eva@example.com",
    studentAvatar: "EM",
    assessmentTitle: "Python Basics — Week 1",
    score: 76,
    passed: true,
    timeAgo: "3 hours ago",
    timestamp: "2024-05-25 12:00",
  },
];

export const mockStudentReports: Record<string, StudentReportItem[]> = {
  "alice@example.com": [
    {
      id: "rep-101",
      assessmentId: "asm-1",
      assessmentTitle: "Python Basics — Week 1",
      score: 94,
      maxScore: 100,
      percentage: 94,
      dateTaken: "May 24, 2024",
      timeSpent: "32 mins",
      status: "Passed",
      department: "Computer Science",
      topics: [
        { name: "Syntax & Variables", score: 100 },
        { name: "Control Flow & Loops", score: 92 },
        { name: "List Comprehensions", score: 90 },
      ],
    },
    {
      id: "rep-102",
      assessmentId: "asm-2",
      assessmentTitle: "Core Java & OOP Concepts",
      score: 90,
      maxScore: 100,
      percentage: 90,
      dateTaken: "May 18, 2024",
      timeSpent: "48 mins",
      status: "Passed",
      department: "Computer Science",
      topics: [
        { name: "Polymorphism & Inheritance", score: 95 },
        { name: "Collections Framework", score: 85 },
      ],
    },
    {
      id: "rep-103",
      assessmentId: "asm-3",
      assessmentTitle: "Relational Database Design & SQL",
      score: 92,
      maxScore: 100,
      percentage: 92,
      dateTaken: "May 10, 2024",
      timeSpent: "41 mins",
      status: "Passed",
      department: "Computer Science",
      topics: [
        { name: "Normalization", score: 90 },
        { name: "Complex JOIN Queries", score: 94 },
      ],
    },
  ],
  "bob@example.com": [
    {
      id: "rep-201",
      assessmentId: "asm-2",
      assessmentTitle: "Core Java & OOP Concepts",
      score: 85,
      maxScore: 100,
      percentage: 85,
      dateTaken: "May 25, 2024",
      timeSpent: "54 mins",
      status: "Passed",
      department: "Information Technology",
      topics: [
        { name: "Polymorphism & Inheritance", score: 88 },
        { name: "Collections Framework", score: 82 },
      ],
    },
    {
      id: "rep-202",
      assessmentId: "asm-1",
      assessmentTitle: "Python Basics — Week 1",
      score: 85,
      maxScore: 100,
      percentage: 85,
      dateTaken: "May 15, 2024",
      timeSpent: "39 mins",
      status: "Passed",
      department: "Information Technology",
      topics: [
        { name: "Syntax & Variables", score: 90 },
        { name: "Control Flow & Loops", score: 80 },
      ],
    },
  ],
  "carol@example.com": [
    {
      id: "rep-301",
      assessmentId: "asm-5",
      assessmentTitle: "Data Structures & Algorithms Sprint",
      score: 90,
      maxScore: 100,
      percentage: 90,
      dateTaken: "May 25, 2024",
      timeSpent: "74 mins",
      status: "Passed",
      department: "Computer Science",
      topics: [
        { name: "Binary Trees & BST", score: 94 },
        { name: "Dynamic Programming", score: 86 },
      ],
    },
    {
      id: "rep-302",
      assessmentId: "asm-3",
      assessmentTitle: "Relational Database Design & SQL",
      score: 86,
      maxScore: 100,
      percentage: 86,
      dateTaken: "May 19, 2024",
      timeSpent: "46 mins",
      status: "Passed",
      department: "Computer Science",
      topics: [
        { name: "Indexing", score: 82 },
        { name: "Transactions & ACID", score: 90 },
      ],
    },
  ],
  "david@example.com": [
    {
      id: "rep-401",
      assessmentId: "asm-1",
      assessmentTitle: "Python Basics — Week 1",
      score: 72,
      maxScore: 100,
      percentage: 72,
      dateTaken: "May 08, 2024",
      timeSpent: "44 mins",
      status: "Passed",
      department: "Electronics",
      topics: [
        { name: "Syntax & Variables", score: 80 },
        { name: "Control Flow & Loops", score: 64 },
      ],
    },
    {
      id: "rep-402",
      assessmentId: "asm-2",
      assessmentTitle: "Core Java & OOP Concepts",
      score: 58,
      maxScore: 100,
      percentage: 58,
      dateTaken: "April 29, 2024",
      timeSpent: "59 mins",
      status: "Failed",
      department: "Electronics",
      topics: [
        { name: "Polymorphism & Inheritance", score: 60 },
        { name: "Memory Model", score: 55 },
      ],
    },
  ],
  "eva@example.com": [
    {
      id: "rep-501",
      assessmentId: "asm-1",
      assessmentTitle: "Python Basics — Week 1",
      score: 78,
      maxScore: 100,
      percentage: 78,
      dateTaken: "May 25, 2024",
      timeSpent: "37 mins",
      status: "Passed",
      department: "Computer Science",
      topics: [
        { name: "Syntax & Variables", score: 88 },
        { name: "List Comprehensions", score: 68 },
      ],
    },
  ],
  "frank@example.com": [
    {
      id: "rep-601",
      assessmentId: "asm-3",
      assessmentTitle: "Relational Database Design & SQL",
      score: 82,
      maxScore: 100,
      percentage: 82,
      dateTaken: "May 25, 2024",
      timeSpent: "43 mins",
      status: "Passed",
      department: "Information Technology",
      topics: [
        { name: "Normalization", score: 85 },
        { name: "JOIN Queries", score: 80 },
      ],
    },
  ],
};

export const mockInstitutionDashboardMetrics: any = {
  totalStudents: 480,
  activeBatchesCount: 8,
  todayAttendanceRate: 94.2,
  todayPresentCount: 452,
  todayAbsentCount: 28,
  totalFacultyCount: 24,
  pendingApprovalsCount: 3,
  activeAnnouncementsCount: 4,
  lowAttendanceStudentCount: 5,
};

export const mockBatches: any[] = [
  {
    id: "batch-cs-26a",
    institutionId: "inst-stanford",
    name: "CS 2026 - Section A",
    code: "CS-26-A",
    department: "Computer Science & Engineering",
    academicYear: 2026,
    batchYear: 2026,
    semester: 6,
    section: "A",
    facultyIds: ["fac-101"],
    facultyNames: ["Prof. David Malan"],
    assignedFacultyIds: ["fac-101"],
    assignedFacultyNames: ["Prof. David Malan"],
    studentCount: 45,
    studentIds: [1, 2, 3, 4],
    schedules: [
      {
        id: "sch-101",
        dayOfWeek: "Monday",
        startTime: "09:00",
        endTime: "10:30",
        subjectCode: "CS301",
        subjectName: "Advanced Data Structures & Algorithms",
        venueRoom: "Turing Hall 301",
        facultyId: "fac-101",
        facultyName: "Prof. David Malan",
      },
    ],
    scheduleWindows: [
      {
        id: "sch-101",
        dayOfWeek: "Monday",
        startTime: "09:00",
        endTime: "10:30",
        subjectCode: "CS301",
        subjectName: "Advanced Data Structures & Algorithms",
        venueRoom: "Turing Hall 301",
        facultyId: "fac-101",
        facultyName: "Prof. David Malan",
      },
    ],
    status: "ACTIVE",
    createdAt: "2026-01-10",
  },
  {
    id: "batch-cs-26b",
    institutionId: "inst-stanford",
    name: "CS 2026 - Section B",
    code: "CS-26-B",
    department: "Computer Science & Engineering",
    academicYear: 2026,
    batchYear: 2026,
    semester: 6,
    section: "B",
    facultyIds: ["fac-102"],
    facultyNames: ["Dr. Evelyn Vance"],
    assignedFacultyIds: ["fac-102"],
    assignedFacultyNames: ["Dr. Evelyn Vance"],
    studentCount: 42,
    studentIds: [5, 6, 7],
    schedules: [
      {
        id: "sch-102",
        dayOfWeek: "Tuesday",
        startTime: "11:00",
        endTime: "12:30",
        subjectCode: "CS302",
        subjectName: "Operating Systems & Concurrency",
        venueRoom: "Hopper Lab 204",
        facultyId: "fac-102",
        facultyName: "Dr. Evelyn Vance",
      },
    ],
    scheduleWindows: [
      {
        id: "sch-102",
        dayOfWeek: "Tuesday",
        startTime: "11:00",
        endTime: "12:30",
        subjectCode: "CS302",
        subjectName: "Operating Systems & Concurrency",
        venueRoom: "Hopper Lab 204",
        facultyId: "fac-102",
        facultyName: "Dr. Evelyn Vance",
      },
    ],
    status: "ACTIVE",
    createdAt: "2026-01-10",
  },
  {
    id: "batch-it-26a",
    institutionId: "inst-stanford",
    name: "IT 2026 - Section A",
    code: "IT-26-A",
    department: "Information Technology",
    academicYear: 2026,
    batchYear: 2026,
    semester: 6,
    section: "A",
    facultyIds: ["fac-103"],
    facultyNames: ["Prof. Marcus Brody"],
    assignedFacultyIds: ["fac-103"],
    assignedFacultyNames: ["Prof. Marcus Brody"],
    studentCount: 38,
    studentIds: [8, 9],
    schedules: [
      {
        id: "sch-103",
        dayOfWeek: "Wednesday",
        startTime: "14:00",
        endTime: "15:30",
        subjectCode: "IT304",
        subjectName: "Cloud Computing & Microservices",
        venueRoom: "Gates Building 110",
        facultyId: "fac-103",
        facultyName: "Prof. Marcus Brody",
      },
    ],
    scheduleWindows: [
      {
        id: "sch-103",
        dayOfWeek: "Wednesday",
        startTime: "14:00",
        endTime: "15:30",
        subjectCode: "IT304",
        subjectName: "Cloud Computing & Microservices",
        venueRoom: "Gates Building 110",
        facultyId: "fac-103",
        facultyName: "Prof. Marcus Brody",
      },
    ],
    status: "ACTIVE",
    createdAt: "2026-01-12",
  },
];

export const mockStaffFaculty: any[] = [
  {
    id: "fac-101",
    institutionId: "inst-stanford",
    name: "Prof. David Malan",
    email: "david.malan@stanford.edu",
    employeeId: "STAN-FAC-101",
    role: "FACULTY_STAFF",
    department: "Computer Science & Engineering",
    designation: "Professor of the Practice",
    assignedBatchIds: ["batch-cs-26a"],
    assignedBatchNames: ["CS 2026 - Section A"],
    assignedSubjects: ["Advanced Data Structures & Algorithms"],
    phone: "+1 (650) 723-2300",
    avatarColor: "bg-blue-600",
    status: "ACTIVE",
    mobileAppAccess: true,
    mobileApiKey: "th_live_fac_david_malan_782910a",
    apiKey: "th_live_fac_david_malan_782910a",
    lastLoginAt: "Today, 08:45 AM",
    lastMobileSyncAt: "Today, 09:05 AM",
    createdAt: "2025-08-01",
  },
  {
    id: "fac-102",
    institutionId: "inst-stanford",
    name: "Dr. Evelyn Vance",
    email: "evelyn.vance@stanford.edu",
    employeeId: "STAN-FAC-102",
    role: "FACULTY_STAFF",
    department: "Computer Science & Engineering",
    designation: "Associate Professor",
    assignedBatchIds: ["batch-cs-26b"],
    assignedBatchNames: ["CS 2026 - Section B"],
    assignedSubjects: ["Operating Systems & Concurrency"],
    phone: "+1 (650) 723-4412",
    avatarColor: "bg-purple-600",
    status: "ACTIVE",
    mobileAppAccess: true,
    mobileApiKey: "th_live_fac_evelyn_vance_99381b",
    apiKey: "th_live_fac_evelyn_vance_99381b",
    lastLoginAt: "Yesterday, 04:15 PM",
    lastMobileSyncAt: "Today, 08:30 AM",
    createdAt: "2025-08-01",
  },
  {
    id: "fac-103",
    institutionId: "inst-stanford",
    name: "Prof. Marcus Brody",
    email: "marcus.brody@stanford.edu",
    employeeId: "STAN-FAC-103",
    role: "FACULTY_STAFF",
    department: "Information Technology",
    designation: "Assistant Professor",
    assignedBatchIds: ["batch-it-26a"],
    assignedBatchNames: ["IT 2026 - Section A"],
    assignedSubjects: ["Cloud Computing & Microservices"],
    phone: "+1 (650) 723-5590",
    avatarColor: "bg-emerald-600",
    status: "ACTIVE",
    mobileAppAccess: true,
    mobileApiKey: "th_live_fac_marcus_brody_44123c",
    apiKey: "th_live_fac_marcus_brody_44123c",
    lastLoginAt: "Today, 07:50 AM",
    lastMobileSyncAt: "Today, 08:00 AM",
    createdAt: "2025-08-15",
  },
];

export const mockAttendanceRecords: any[] = [
  {
    id: "att-rec-101",
    institutionId: "inst-stanford",
    batchId: "batch-cs-26a",
    batchName: "CS 2026 - Section A",
    subjectName: "Advanced Data Structures & Algorithms",
    studentId: 1,
    studentName: "Naveen Kumar",
    registerNumber: "710022104052",
    netId: "nkumar26",
    studentEmail: "naveen.kumar@stanford.edu",
    date: new Date().toISOString().split("T")[0],
    sessionTimeWindow: "09:00 - 10:30",
    status: "PRESENT",
    source: "mobile-app",
    markedAt: "2026-08-31T09:02:14Z",
    markedByUserId: "fac-101",
    markedByName: "Prof. David Malan",
    venueRoom: "Turing Hall 301",
    syncStatus: "SYNCED",
  },
  {
    id: "att-rec-102",
    institutionId: "inst-stanford",
    batchId: "batch-cs-26a",
    batchName: "CS 2026 - Section A",
    subjectName: "Advanced Data Structures & Algorithms",
    studentId: 2,
    studentName: "Aarav Sharma",
    registerNumber: "710022104001",
    netId: "asharma26",
    studentEmail: "aarav.sharma@stanford.edu",
    date: new Date().toISOString().split("T")[0],
    sessionTimeWindow: "09:00 - 10:30",
    status: "PRESENT",
    source: "mobile-app",
    markedAt: "2026-08-31T09:03:00Z",
    markedByUserId: "fac-101",
    markedByName: "Prof. David Malan",
    venueRoom: "Turing Hall 301",
    syncStatus: "SYNCED",
  },
  {
    id: "att-rec-103",
    institutionId: "inst-stanford",
    batchId: "batch-cs-26a",
    batchName: "CS 2026 - Section A",
    subjectName: "Advanced Data Structures & Algorithms",
    studentId: 3,
    studentName: "Diya Patel",
    registerNumber: "710022104015",
    netId: "dpatel26",
    studentEmail: "diya.patel@stanford.edu",
    date: new Date().toISOString().split("T")[0],
    sessionTimeWindow: "09:00 - 10:30",
    status: "LATE",
    source: "web-manual",
    markedAt: "2026-08-31T09:18:22Z",
    markedByUserId: "fac-101",
    markedByName: "Prof. David Malan",
    venueRoom: "Turing Hall 301",
    remarks: "Arrived at 09:18 AM due to transit delay",
    syncStatus: "SYNCED",
  },
  {
    id: "att-rec-104",
    institutionId: "inst-stanford",
    batchId: "batch-cs-26a",
    batchName: "CS 2026 - Section A",
    subjectName: "Advanced Data Structures & Algorithms",
    studentId: 4,
    studentName: "Rohan Gupta",
    registerNumber: "710022104038",
    netId: "rgupta26",
    studentEmail: "rohan.gupta@stanford.edu",
    date: new Date().toISOString().split("T")[0],
    sessionTimeWindow: "09:00 - 10:30",
    status: "ABSENT",
    source: "web-manual",
    markedAt: "2026-08-31T09:30:00Z",
    markedByUserId: "fac-101",
    markedByName: "Prof. David Malan",
    venueRoom: "Turing Hall 301",
    syncStatus: "SYNCED",
  },
];

export const mockInstitutionAnnouncements: any[] = [
  {
    id: "ann-101",
    institutionId: "inst-stanford",
    title: "Midterm Assessment Proctoring Guidelines — Fall 2026",
    content:
      "All proctors must ensure candidates check in via mobile scanner or manual roster at least 15 minutes before the assessment start time. Safe Exam Browser (SEB) keys must be verified prior to distributing workstation codes.",
    targetType: "FACULTY",
    targetAudience: "FACULTY",
    authorId: "user-inst-admin",
    authorName: "Dr. Arthur Mitchell",
    authorRole: "Dean of Academic Affairs",
    priority: "HIGH",
    pinned: true,
    createdAt: "2026-08-28",
    publishedAt: "Aug 28, 2026, 09:00 AM",
    readCount: 38,
  },
  {
    id: "ann-102",
    institutionId: "inst-stanford",
    title: "Turing Hall Network Maintenance Scheduled for Saturday",
    content:
      "Please note that the wired local area network and RFID gateways in Turing Hall 301-305 will undergo routine maintenance from 06:00 to 11:00 AM this Saturday. Offline mobile marking mode should be utilized for morning sessions.",
    targetType: "ALL",
    targetAudience: "ALL",
    authorId: "user-it-admin",
    authorName: "Campus IT Infrastructure",
    authorRole: "Systems Operations",
    priority: "NORMAL",
    pinned: false,
    createdAt: "2026-08-30",
    publishedAt: "Aug 30, 2026, 02:30 PM",
    readCount: 142,
  },
];

