import {
  Batch,
  StaffFaculty,
  AttendanceRecord,
  InstitutionAnnouncement,
  Student,
  BatchScheduleWindow,
  MobileSyncDataset,
} from './types';

export const mockStaffFaculty: StaffFaculty[] = [
  {
    id: 'fac-101',
    institutionId: 'inst-stanford',
    name: 'Prof. David Malan',
    email: 'david.malan@stanford.edu',
    employeeId: 'FAC-CS-101',
    role: 'FACULTY_STAFF',
    department: 'Computer Science',
    designation: 'Senior Professor of Computing',
    assignedBatchIds: ['batch-cs-26a', 'batch-cs-26b'],
    phone: '+1 (650) 723-4101',
    status: 'ACTIVE',
    mobileAppAccess: true,
    mobileApiKey: 'th_mob_key_malan_78a19bc',
    lastLoginAt: '2026-08-31T09:15:00Z',
    lastMobileSyncAt: '2026-08-31T09:20:00Z',
    createdAt: '2025-08-10T08:00:00Z',
  },
  {
    id: 'fac-102',
    institutionId: 'inst-stanford',
    name: 'Dr. Sarah Chen',
    email: 'sarah.chen@stanford.edu',
    employeeId: 'FAC-CS-102',
    role: 'INSTITUTION_ADMIN',
    department: 'Computer Science',
    designation: 'Associate Dean of Academic Systems',
    assignedBatchIds: ['batch-cs-26a', 'batch-aiml-26'],
    phone: '+1 (650) 723-4102',
    status: 'ACTIVE',
    mobileAppAccess: true,
    mobileApiKey: 'th_mob_key_chen_92b43ef',
    lastLoginAt: '2026-08-31T10:45:00Z',
    lastMobileSyncAt: '2026-08-31T10:50:00Z',
    createdAt: '2025-06-15T08:00:00Z',
  },
  {
    id: 'fac-103',
    institutionId: 'inst-stanford',
    name: 'Prof. Elena Rostova',
    email: 'elena.r@stanford.edu',
    employeeId: 'FAC-AI-103',
    role: 'DEPARTMENT_HEAD',
    department: 'Artificial Intelligence',
    designation: 'Head of Department & Professor',
    assignedBatchIds: ['batch-aiml-26'],
    phone: '+1 (650) 723-4103',
    status: 'ACTIVE',
    mobileAppAccess: true,
    mobileApiKey: 'th_mob_key_rostova_33c91df',
    lastLoginAt: '2026-08-30T16:20:00Z',
    lastMobileSyncAt: '2026-08-30T16:22:00Z',
    createdAt: '2025-07-01T08:00:00Z',
  },
  {
    id: 'fac-104',
    institutionId: 'inst-stanford',
    name: 'Dr. Marcus Brody',
    email: 'm.brody@stanford.edu',
    employeeId: 'FAC-IS-104',
    role: 'FACULTY_STAFF',
    department: 'Information Systems',
    designation: 'Assistant Professor',
    assignedBatchIds: ['batch-is-26c'],
    phone: '+1 (650) 723-4104',
    status: 'ACTIVE',
    mobileAppAccess: false,
    mobileApiKey: 'th_mob_key_brody_44d28aa',
    lastLoginAt: '2026-08-29T11:00:00Z',
    createdAt: '2025-09-01T08:00:00Z',
  },
];

export const mockBatches: Batch[] = [
  {
    id: 'batch-cs-26a',
    institutionId: 'inst-stanford',
    name: 'CS 2026 - Section A',
    code: 'CS-26-A',
    department: 'Computer Science & Engineering',
    batchYear: 2026,
    semester: 6,
    section: 'A',
    facultyIds: ['fac-101', 'fac-102'],
    facultyNames: ['Prof. David Malan', 'Dr. Sarah Chen'],
    studentCount: 8,
    studentIds: [0, 1, 2, 3, 4, 5, 6, 7],
    status: 'ACTIVE',
    createdAt: '2026-01-10T08:00:00Z',
    schedules: [
      {
        id: 'sch-cs-101',
        dayOfWeek: 'Monday',
        startTime: '09:00',
        endTime: '10:30',
        subjectCode: 'CS301',
        subjectName: 'Advanced Data Structures & Algorithms',
        venueRoom: 'Turing Hall 301',
        facultyId: 'fac-101',
        facultyName: 'Prof. David Malan',
      },
      {
        id: 'sch-cs-102',
        dayOfWeek: 'Wednesday',
        startTime: '11:00',
        endTime: '12:30',
        subjectCode: 'CS305',
        subjectName: 'Operating Systems & Kernel Design',
        venueRoom: 'Gates Computing Lab B4',
        facultyId: 'fac-102',
        facultyName: 'Dr. Sarah Chen',
      },
      {
        id: 'sch-cs-103',
        dayOfWeek: 'Friday',
        startTime: '14:00',
        endTime: '15:30',
        subjectCode: 'CS310',
        subjectName: 'Distributed Cloud Systems',
        venueRoom: 'Turing Hall 301',
        facultyId: 'fac-102',
        facultyName: 'Dr. Sarah Chen',
      },
    ],
  },
  {
    id: 'batch-cs-26b',
    institutionId: 'inst-stanford',
    name: 'CS 2026 - Section B',
    code: 'CS-26-B',
    department: 'Computer Science & Engineering',
    batchYear: 2026,
    semester: 6,
    section: 'B',
    facultyIds: ['fac-101'],
    facultyNames: ['Prof. David Malan'],
    studentCount: 5,
    studentIds: [8, 9, 10, 11, 12],
    status: 'ACTIVE',
    createdAt: '2026-01-10T08:00:00Z',
    schedules: [
      {
        id: 'sch-cs-201',
        dayOfWeek: 'Tuesday',
        startTime: '10:00',
        endTime: '11:30',
        subjectCode: 'CS301',
        subjectName: 'Advanced Data Structures & Algorithms',
        venueRoom: 'Turing Hall 302',
        facultyId: 'fac-101',
        facultyName: 'Prof. David Malan',
      },
      {
        id: 'sch-cs-202',
        dayOfWeek: 'Thursday',
        startTime: '14:00',
        endTime: '15:30',
        subjectCode: 'CS308',
        subjectName: 'Database Storage & Query Optimization',
        venueRoom: 'Packard Lab 108',
        facultyId: 'fac-101',
        facultyName: 'Prof. David Malan',
      },
    ],
  },
  {
    id: 'batch-aiml-26',
    institutionId: 'inst-stanford',
    name: 'AI & Machine Learning Cohort 2026',
    code: 'AIML-26',
    department: 'Artificial Intelligence',
    batchYear: 2026,
    semester: 6,
    section: 'AI-1',
    facultyIds: ['fac-102', 'fac-103'],
    facultyNames: ['Dr. Sarah Chen', 'Prof. Elena Rostova'],
    studentCount: 4,
    studentIds: [13, 14, 15, 16],
    status: 'ACTIVE',
    createdAt: '2026-01-12T08:00:00Z',
    schedules: [
      {
        id: 'sch-ai-301',
        dayOfWeek: 'Monday',
        startTime: '14:00',
        endTime: '16:00',
        subjectCode: 'AI402',
        subjectName: 'Deep Neural Networks & Transformer Architectures',
        venueRoom: 'AI Research Lab 1',
        facultyId: 'fac-103',
        facultyName: 'Prof. Elena Rostova',
      },
      {
        id: 'sch-ai-302',
        dayOfWeek: 'Thursday',
        startTime: '09:00',
        endTime: '10:30',
        subjectCode: 'AI408',
        subjectName: 'Reinforcement Learning & Autonomous Agents',
        venueRoom: 'Robotics Bay 2',
        facultyId: 'fac-102',
        facultyName: 'Dr. Sarah Chen',
      },
    ],
  },
  {
    id: 'batch-is-26c',
    institutionId: 'inst-stanford',
    name: 'Information Systems 2026 - Section C',
    code: 'IS-26-C',
    department: 'Information Systems',
    batchYear: 2026,
    semester: 6,
    section: 'C',
    facultyIds: ['fac-104'],
    facultyNames: ['Dr. Marcus Brody'],
    studentCount: 3,
    studentIds: [17, 18, 19],
    status: 'ACTIVE',
    createdAt: '2026-01-15T08:00:00Z',
    schedules: [
      {
        id: 'sch-is-401',
        dayOfWeek: 'Wednesday',
        startTime: '09:00',
        endTime: '10:30',
        subjectCode: 'IS302',
        subjectName: 'Enterprise Cybersecurity & Zero Trust',
        venueRoom: 'Security Lab 201',
        facultyId: 'fac-104',
        facultyName: 'Dr. Marcus Brody',
      },
    ],
  },
];

export const mockAttendanceRecords: AttendanceRecord[] = [
  // Today's Session: Monday 09:00 - 10:30, CS301 (CS-26-A)
  {
    id: 'att-20260831-00',
    institutionId: 'inst-stanford',
    batchId: 'batch-cs-26a',
    batchName: 'CS 2026 - Section A',
    scheduleWindowId: 'sch-cs-101',
    subjectName: 'Advanced Data Structures & Algorithms',
    studentId: 0,
    studentName: 'Nanda Kumar',
    registerNumber: '710022104052',
    netId: 'nkumar26',
    studentEmail: 'nanda@talhelix.com',
    date: '2026-08-31',
    sessionTimeWindow: '09:00 - 10:30',
    status: 'PRESENT',
    source: 'mobile-app',
    markedAt: '2026-08-31T09:04:12Z',
    markedByUserId: 'fac-101',
    markedByName: 'Prof. David Malan',
    venueRoom: 'Turing Hall 301',
    syncStatus: 'SYNCED',
  },
  {
    id: 'att-20260831-01',
    institutionId: 'inst-stanford',
    batchId: 'batch-cs-26a',
    batchName: 'CS 2026 - Section A',
    scheduleWindowId: 'sch-cs-101',
    subjectName: 'Advanced Data Structures & Algorithms',
    studentId: 1,
    studentName: 'Alice Johnson',
    registerNumber: '710022104001',
    netId: 'ajohnson26',
    studentEmail: 'alice@example.com',
    date: '2026-08-31',
    sessionTimeWindow: '09:00 - 10:30',
    status: 'PRESENT',
    source: 'mobile-app',
    markedAt: '2026-08-31T09:05:30Z',
    markedByUserId: 'fac-101',
    markedByName: 'Prof. David Malan',
    venueRoom: 'Turing Hall 301',
    syncStatus: 'SYNCED',
  },
  {
    id: 'att-20260831-02',
    institutionId: 'inst-stanford',
    batchId: 'batch-cs-26a',
    batchName: 'CS 2026 - Section A',
    scheduleWindowId: 'sch-cs-101',
    subjectName: 'Advanced Data Structures & Algorithms',
    studentId: 2,
    studentName: 'Bob Smith',
    registerNumber: '710022104002',
    netId: 'bsmith26',
    studentEmail: 'bob@example.com',
    date: '2026-08-31',
    sessionTimeWindow: '09:00 - 10:30',
    status: 'LATE',
    source: 'web-manual',
    markedAt: '2026-08-31T09:18:22Z',
    markedByUserId: 'fac-101',
    markedByName: 'Prof. David Malan',
    venueRoom: 'Turing Hall 301',
    remarks: 'Arrived at 9:18 AM due to transit delay',
    syncStatus: 'SYNCED',
  },
  {
    id: 'att-20260831-03',
    institutionId: 'inst-stanford',
    batchId: 'batch-cs-26a',
    batchName: 'CS 2026 - Section A',
    scheduleWindowId: 'sch-cs-101',
    subjectName: 'Advanced Data Structures & Algorithms',
    studentId: 3,
    studentName: 'Charlie Davis',
    registerNumber: '710022104003',
    netId: 'cdavis26',
    studentEmail: 'charlie@example.com',
    date: '2026-08-31',
    sessionTimeWindow: '09:00 - 10:30',
    status: 'ABSENT',
    source: 'web-manual',
    markedAt: '2026-08-31T09:30:00Z',
    markedByUserId: 'fac-101',
    markedByName: 'Prof. David Malan',
    venueRoom: 'Turing Hall 301',
    syncStatus: 'SYNCED',
  },
  {
    id: 'att-20260831-04',
    institutionId: 'inst-stanford',
    batchId: 'batch-cs-26a',
    batchName: 'CS 2026 - Section A',
    scheduleWindowId: 'sch-cs-101',
    subjectName: 'Advanced Data Structures & Algorithms',
    studentId: 4,
    studentName: 'Diana Prince',
    registerNumber: '710022104004',
    netId: 'dprince26',
    studentEmail: 'diana@example.com',
    date: '2026-08-31',
    sessionTimeWindow: '09:00 - 10:30',
    status: 'PRESENT',
    source: 'rfid',
    markedAt: '2026-08-31T08:58:14Z',
    markedByUserId: 'rfid-gate-turing301',
    markedByName: 'Turing Hall RFID Turnstile',
    venueRoom: 'Turing Hall 301',
    syncStatus: 'SYNCED',
  },
  {
    id: 'att-20260831-05',
    institutionId: 'inst-stanford',
    batchId: 'batch-cs-26a',
    batchName: 'CS 2026 - Section A',
    scheduleWindowId: 'sch-cs-101',
    subjectName: 'Advanced Data Structures & Algorithms',
    studentId: 5,
    studentName: 'Evan Wright',
    registerNumber: '710022104005',
    netId: 'ewright26',
    studentEmail: 'evan@example.com',
    date: '2026-08-31',
    sessionTimeWindow: '09:00 - 10:30',
    status: 'PRESENT',
    source: 'mobile-app',
    markedAt: '2026-08-31T09:02:45Z',
    markedByUserId: 'fac-101',
    markedByName: 'Prof. David Malan',
    venueRoom: 'Turing Hall 301',
    syncStatus: 'SYNCED',
  },
  {
    id: 'att-20260831-06',
    institutionId: 'inst-stanford',
    batchId: 'batch-cs-26a',
    batchName: 'CS 2026 - Section A',
    scheduleWindowId: 'sch-cs-101',
    subjectName: 'Advanced Data Structures & Algorithms',
    studentId: 6,
    studentName: 'Fiona Gallagher',
    registerNumber: '710022104006',
    netId: 'fgallagher26',
    studentEmail: 'fiona@example.com',
    date: '2026-08-31',
    sessionTimeWindow: '09:00 - 10:30',
    status: 'PRESENT',
    source: 'mobile-app',
    markedAt: '2026-08-31T09:03:10Z',
    markedByUserId: 'fac-101',
    markedByName: 'Prof. David Malan',
    venueRoom: 'Turing Hall 301',
    syncStatus: 'SYNCED',
  },
  {
    id: 'att-20260831-07',
    institutionId: 'inst-stanford',
    batchId: 'batch-cs-26a',
    batchName: 'CS 2026 - Section A',
    scheduleWindowId: 'sch-cs-101',
    subjectName: 'Advanced Data Structures & Algorithms',
    studentId: 7,
    studentName: 'George Clark',
    registerNumber: '710022104007',
    netId: 'gclark26',
    studentEmail: 'george@example.com',
    date: '2026-08-31',
    sessionTimeWindow: '09:00 - 10:30',
    status: 'ABSENT',
    source: 'web-manual',
    markedAt: '2026-08-31T09:30:00Z',
    markedByUserId: 'fac-101',
    markedByName: 'Prof. David Malan',
    venueRoom: 'Turing Hall 301',
    syncStatus: 'SYNCED',
  },

  // Historical Records (Friday 2026-08-28)
  {
    id: 'att-20260828-00',
    institutionId: 'inst-stanford',
    batchId: 'batch-cs-26a',
    batchName: 'CS 2026 - Section A',
    scheduleWindowId: 'sch-cs-103',
    subjectName: 'Distributed Cloud Systems',
    studentId: 0,
    studentName: 'Nanda Kumar',
    registerNumber: '710022104052',
    netId: 'nkumar26',
    studentEmail: 'nanda@talhelix.com',
    date: '2026-08-28',
    sessionTimeWindow: '14:00 - 15:30',
    status: 'PRESENT',
    source: 'mobile-app',
    markedAt: '2026-08-28T14:02:10Z',
    markedByUserId: 'fac-102',
    markedByName: 'Dr. Sarah Chen',
    venueRoom: 'Turing Hall 301',
    syncStatus: 'SYNCED',
  },
  {
    id: 'att-20260828-01',
    institutionId: 'inst-stanford',
    batchId: 'batch-cs-26a',
    batchName: 'CS 2026 - Section A',
    scheduleWindowId: 'sch-cs-103',
    subjectName: 'Distributed Cloud Systems',
    studentId: 1,
    studentName: 'Alice Johnson',
    registerNumber: '710022104001',
    netId: 'ajohnson26',
    studentEmail: 'alice@example.com',
    date: '2026-08-28',
    sessionTimeWindow: '14:00 - 15:30',
    status: 'PRESENT',
    source: 'mobile-app',
    markedAt: '2026-08-28T14:03:00Z',
    markedByUserId: 'fac-102',
    markedByName: 'Dr. Sarah Chen',
    venueRoom: 'Turing Hall 301',
    syncStatus: 'SYNCED',
  },
  {
    id: 'att-20260828-02',
    institutionId: 'inst-stanford',
    batchId: 'batch-cs-26a',
    batchName: 'CS 2026 - Section A',
    scheduleWindowId: 'sch-cs-103',
    subjectName: 'Distributed Cloud Systems',
    studentId: 2,
    studentName: 'Bob Smith',
    registerNumber: '710022104002',
    netId: 'bsmith26',
    studentEmail: 'bob@example.com',
    date: '2026-08-28',
    sessionTimeWindow: '14:00 - 15:30',
    status: 'ABSENT',
    source: 'web-manual',
    markedAt: '2026-08-28T14:15:00Z',
    markedByUserId: 'fac-102',
    markedByName: 'Dr. Sarah Chen',
    venueRoom: 'Turing Hall 301',
    syncStatus: 'SYNCED',
  },
];

export const mockAnnouncements: InstitutionAnnouncement[] = [
  {
    id: 'anc-01',
    institutionId: 'inst-stanford',
    title: 'Mid-Term Technical Assessments & Proctored Coding Schedule',
    content:
      'All students enrolled in CS 2026 Sections A & B and AIML-26 cohorts are required to complete the upcoming proctored DSA coding assessments via the TalHelix portal. Ensure your device meets the Safe Exam Browser criteria.',
    targetType: 'ALL',
    authorId: 'fac-102',
    authorName: 'Dr. Sarah Chen',
    authorRole: 'Associate Dean of Academic Systems',
    priority: 'HIGH',
    createdAt: '2026-08-29T10:00:00Z',
    publishedAt: '2026-08-29T10:00:00Z',
    readCount: 142,
  },
  {
    id: 'anc-02',
    institutionId: 'inst-stanford',
    title: 'Mandatory 75% Attendance Requirement for Placement Clearances',
    content:
      'University guidelines mandate a minimum of 75% verified laboratory and lecture attendance for eligibility in forthcoming institutional placement drives and enterprise hackathons.',
    targetType: 'STUDENTS',
    authorId: 'fac-103',
    authorName: 'Prof. Elena Rostova',
    authorRole: 'Head of Department',
    priority: 'URGENT',
    createdAt: '2026-08-25T14:30:00Z',
    publishedAt: '2026-08-25T14:30:00Z',
    readCount: 218,
  },
  {
    id: 'anc-03',
    institutionId: 'inst-stanford',
    title: 'Mobile Attendance App API Credentials & Faculty Pilot',
    content:
      'Faculty members can now scan student attendance using their registered mobile app API keys. Live synchronization runs automatically with the central TalHelix registry.',
    targetType: 'FACULTY',
    authorId: 'fac-102',
    authorName: 'Dr. Sarah Chen',
    authorRole: 'Associate Dean of Academic Systems',
    priority: 'NORMAL',
    createdAt: '2026-08-20T09:00:00Z',
    publishedAt: '2026-08-20T09:00:00Z',
    readCount: 45,
  },
];
